services:
 php:
  build: server/php
  volumes:
   - ./image:/var/www/html/images:ro
  ports:
   - 8080:80
 golang:
  build: server/golang
  volumes:
   - ./image:/app/images:ro
  ports:
   - 8081:8080
 rust:
  build: server/rust
  volumes:
   - ./image:/app/images:ro
  ports:
   - 8082:8080